
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-7pm-4
owner: ucsb-cs156-s23
repo_name: team02-s23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMTk2MzI0","is_bot":false,"login":"ritvibhatt","name":""},"headRefName":"Ritvi-SongController","number":45,"title":"rb - add songs controller","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-4/pull/45"},{"author":{"id":"MDQ6VXNlcjcyODIzMTA3","is_bot":false,"login":"sshivani02","name":""},"headRefName":"Shivani-MovieController","number":44,"title":"ss - added files for movie controller and tests","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-4/pull/44"},{"author":{"id":"MDQ6VXNlcjg2NzAyODU5","is_bot":false,"login":"Joshuason55","name":"Joshua Son"},"headRefName":"JoshhotelController","number":43,"title":"js-Added Controller","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-4/pull/43"},{"author":{"id":"MDQ6VXNlcjUzMTk2MzI0","is_bot":false,"login":"ritvibhatt","name":""},"headRefName":"Ritvi-SongDatabase","number":42,"title":"rb - add song database","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-4/pull/42"},{"author":{"id":"MDQ6VXNlcjcyODIzMTA3","is_bot":false,"login":"sshivani02","name":""},"headRefName":"Shivani-MovieDatabase","number":41,"title":"ss - added database files for Movie entity and repo","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-4/pull/41"},{"author":{"id":"MDQ6VXNlcjgxNjQ5MjU3","is_bot":false,"login":"BrennaScholte","name":"Brenna Scholte"},"headRefName":"Brenna-RestaurantController","number":40,"title":"bs - added restaurant controller","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-4/pull/40"},{"author":{"id":"MDQ6VXNlcjgxNjQ5MjU3","is_bot":false,"login":"BrennaScholte","name":"Brenna Scholte"},"headRefName":"Brenna-RestaurantDatabase","number":39,"title":"bs - add restaurant database","url":"https://github.com/ucsb-cs156-s23/team02-s23-7pm-4/pull/39"}]
